#!/bin/bash
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N d2q9-bgk
#PBS -o 128_d2q9-bgk0.out
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -q teaching

#! Number of nodes (in this case 1 node with 4 CPU cores)
#! The total number of nodes passed to mpirun will be nodes*ppn
#! Second entry: Total amount of wall-clock time (true, elapsed time).
#! 00:05:00 indicates 05 minutes.

#PBS -l nodes=4:ppn=16,walltime=00:02:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_128x128.params obstacles_128x128.dat"

#! Mail to user if job aborts
#PBS -m a

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the parallel MPI executable (nodes*ppn)
mpirun -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options
